apiVersion : v1
kind : Service
metadata :
  name : sketchboard-service
spec:
  selector :
    app: sketchboard-app
  ports:
    - protocol: 'TCP'
      port: 3000
      targetPort: 3000
  type: NodePort